{% set name = "hdf5plugin" %}
{% set version = "2.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 95f03d9d0ec97c40c4e7e9b0438e981329c74e85f4645787786d72b615a0787d

build:
  number: 0
  skip: True  # [win and py<30]

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - pip
    - python
    - setuptools
    - hdf5
  run:
    - h5py
    - python

test:
  imports:
    - hdf5plugin

about:
  home: "https://github.com/silx-kit/hdf5plugin"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "HDF5 Plugins for windows,MacOS and linux"

extra:
  recipe-maintainers:
    - tschoonj
    - t20100
